export const SOCKET_EVENTS = {
  PRICE_TICK: 'PRICE_TICK',
  PRICE_ALERT: 'PRICE_ALERT',
  AI_SCORE_ALERT: 'AI_SCORE_ALERT',
  ORDER_FILLED: 'ORDER_FILLED',
  ORDER_FAILED: 'ORDER_FAILED',
  REPORT_READY: 'REPORT_READY',
  EXECUTION: 'EXECUTION',
  ORDER_PROPOSAL: 'ORDER_PROPOSAL',
} as const
